// Code generated by protoc-gen-go. DO NOT EDIT.
// source: minisns.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Userid               uint32   `protobuf:"varint,3,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Identity             string   `protobuf:"bytes,7,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginResponse) GetUserid() uint32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *LoginResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *LoginResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginResponse) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type LogoutRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{2}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type LogoutResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{3}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LogoutResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type RegisterRequest struct {
	Userid               uint32   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Salt                 string   `protobuf:"bytes,5,opt,name=salt,proto3" json:"salt,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{4}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUserid() uint32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetSalt() string {
	if m != nil {
		return m.Salt
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisterResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{5}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type EditRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditRequest) Reset()         { *m = EditRequest{} }
func (m *EditRequest) String() string { return proto.CompactTextString(m) }
func (*EditRequest) ProtoMessage()    {}
func (*EditRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{6}
}

func (m *EditRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRequest.Unmarshal(m, b)
}
func (m *EditRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRequest.Marshal(b, m, deterministic)
}
func (m *EditRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRequest.Merge(m, src)
}
func (m *EditRequest) XXX_Size() int {
	return xxx_messageInfo_EditRequest.Size(m)
}
func (m *EditRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRequest proto.InternalMessageInfo

func (m *EditRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *EditRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *EditRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *EditRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type EditResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Userid               uint32   `protobuf:"varint,3,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname             string   `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Email                string   `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditResponse) Reset()         { *m = EditResponse{} }
func (m *EditResponse) String() string { return proto.CompactTextString(m) }
func (*EditResponse) ProtoMessage()    {}
func (*EditResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{7}
}

func (m *EditResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditResponse.Unmarshal(m, b)
}
func (m *EditResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditResponse.Marshal(b, m, deterministic)
}
func (m *EditResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditResponse.Merge(m, src)
}
func (m *EditResponse) XXX_Size() int {
	return xxx_messageInfo_EditResponse.Size(m)
}
func (m *EditResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditResponse proto.InternalMessageInfo

func (m *EditResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *EditResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *EditResponse) GetUserid() uint32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *EditResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *EditResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *EditResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type FollowRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Followee             uint32   `protobuf:"varint,2,opt,name=followee,proto3" json:"followee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{8}
}

func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (m *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(m, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *FollowRequest) GetFollowee() uint32 {
	if m != nil {
		return m.Followee
	}
	return 0
}

type FollowResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowResponse) Reset()         { *m = FollowResponse{} }
func (m *FollowResponse) String() string { return proto.CompactTextString(m) }
func (*FollowResponse) ProtoMessage()    {}
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{9}
}

func (m *FollowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowResponse.Unmarshal(m, b)
}
func (m *FollowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowResponse.Marshal(b, m, deterministic)
}
func (m *FollowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowResponse.Merge(m, src)
}
func (m *FollowResponse) XXX_Size() int {
	return xxx_messageInfo_FollowResponse.Size(m)
}
func (m *FollowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowResponse proto.InternalMessageInfo

func (m *FollowResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FollowResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type FollowlistRequest struct {
	Pageno               uint32   `protobuf:"varint,1,opt,name=pageno,proto3" json:"pageno,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Identity             string   `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowlistRequest) Reset()         { *m = FollowlistRequest{} }
func (m *FollowlistRequest) String() string { return proto.CompactTextString(m) }
func (*FollowlistRequest) ProtoMessage()    {}
func (*FollowlistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{10}
}

func (m *FollowlistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowlistRequest.Unmarshal(m, b)
}
func (m *FollowlistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowlistRequest.Marshal(b, m, deterministic)
}
func (m *FollowlistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowlistRequest.Merge(m, src)
}
func (m *FollowlistRequest) XXX_Size() int {
	return xxx_messageInfo_FollowlistRequest.Size(m)
}
func (m *FollowlistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowlistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowlistRequest proto.InternalMessageInfo

func (m *FollowlistRequest) GetPageno() uint32 {
	if m != nil {
		return m.Pageno
	}
	return 0
}

func (m *FollowlistRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *FollowlistRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type SingleUser struct {
	Userid               uint32   `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleUser) Reset()         { *m = SingleUser{} }
func (m *SingleUser) String() string { return proto.CompactTextString(m) }
func (*SingleUser) ProtoMessage()    {}
func (*SingleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{11}
}

func (m *SingleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleUser.Unmarshal(m, b)
}
func (m *SingleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleUser.Marshal(b, m, deterministic)
}
func (m *SingleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleUser.Merge(m, src)
}
func (m *SingleUser) XXX_Size() int {
	return xxx_messageInfo_SingleUser.Size(m)
}
func (m *SingleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleUser.DiscardUnknown(m)
}

var xxx_messageInfo_SingleUser proto.InternalMessageInfo

func (m *SingleUser) GetUserid() uint32 {
	if m != nil {
		return m.Userid
	}
	return 0
}

func (m *SingleUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type FollowlistResponse struct {
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// SingleUser
	Users                []*SingleUser `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FollowlistResponse) Reset()         { *m = FollowlistResponse{} }
func (m *FollowlistResponse) String() string { return proto.CompactTextString(m) }
func (*FollowlistResponse) ProtoMessage()    {}
func (*FollowlistResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{12}
}

func (m *FollowlistResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowlistResponse.Unmarshal(m, b)
}
func (m *FollowlistResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowlistResponse.Marshal(b, m, deterministic)
}
func (m *FollowlistResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowlistResponse.Merge(m, src)
}
func (m *FollowlistResponse) XXX_Size() int {
	return xxx_messageInfo_FollowlistResponse.Size(m)
}
func (m *FollowlistResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowlistResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowlistResponse proto.InternalMessageInfo

func (m *FollowlistResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *FollowlistResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *FollowlistResponse) GetUsers() []*SingleUser {
	if m != nil {
		return m.Users
	}
	return nil
}

type AuthIdentityRequest struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthIdentityRequest) Reset()         { *m = AuthIdentityRequest{} }
func (m *AuthIdentityRequest) String() string { return proto.CompactTextString(m) }
func (*AuthIdentityRequest) ProtoMessage()    {}
func (*AuthIdentityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{13}
}

func (m *AuthIdentityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthIdentityRequest.Unmarshal(m, b)
}
func (m *AuthIdentityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthIdentityRequest.Marshal(b, m, deterministic)
}
func (m *AuthIdentityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthIdentityRequest.Merge(m, src)
}
func (m *AuthIdentityRequest) XXX_Size() int {
	return xxx_messageInfo_AuthIdentityRequest.Size(m)
}
func (m *AuthIdentityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthIdentityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthIdentityRequest proto.InternalMessageInfo

func (m *AuthIdentityRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type AuthIdentityResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthIdentityResponse) Reset()         { *m = AuthIdentityResponse{} }
func (m *AuthIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*AuthIdentityResponse) ProtoMessage()    {}
func (*AuthIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_11307ff29029685d, []int{14}
}

func (m *AuthIdentityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthIdentityResponse.Unmarshal(m, b)
}
func (m *AuthIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthIdentityResponse.Marshal(b, m, deterministic)
}
func (m *AuthIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthIdentityResponse.Merge(m, src)
}
func (m *AuthIdentityResponse) XXX_Size() int {
	return xxx_messageInfo_AuthIdentityResponse.Size(m)
}
func (m *AuthIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthIdentityResponse proto.InternalMessageInfo

func (m *AuthIdentityResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthIdentityResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "proto.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "proto.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "proto.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "proto.LogoutResponse")
	proto.RegisterType((*RegisterRequest)(nil), "proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "proto.RegisterResponse")
	proto.RegisterType((*EditRequest)(nil), "proto.EditRequest")
	proto.RegisterType((*EditResponse)(nil), "proto.EditResponse")
	proto.RegisterType((*FollowRequest)(nil), "proto.FollowRequest")
	proto.RegisterType((*FollowResponse)(nil), "proto.FollowResponse")
	proto.RegisterType((*FollowlistRequest)(nil), "proto.FollowlistRequest")
	proto.RegisterType((*SingleUser)(nil), "proto.SingleUser")
	proto.RegisterType((*FollowlistResponse)(nil), "proto.FollowlistResponse")
	proto.RegisterType((*AuthIdentityRequest)(nil), "proto.AuthIdentityRequest")
	proto.RegisterType((*AuthIdentityResponse)(nil), "proto.AuthIdentityResponse")
}

func init() { proto.RegisterFile("minisns.proto", fileDescriptor_11307ff29029685d) }

var fileDescriptor_11307ff29029685d = []byte{
	// 556 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xde, 0x34, 0x6d, 0x29, 0xd3, 0x16, 0x76, 0xdd, 0xb2, 0x84, 0x70, 0x59, 0xf9, 0xc2, 0x4a,
	0x48, 0x2b, 0xb1, 0xfc, 0x1e, 0x40, 0x02, 0x21, 0x16, 0xad, 0xc4, 0x29, 0x2b, 0x8e, 0x1c, 0x42,
	0x62, 0x82, 0x45, 0x6a, 0x97, 0xd8, 0xa1, 0xe2, 0x55, 0x78, 0x01, 0x1e, 0x81, 0x03, 0x2f, 0x87,
	0x62, 0x3b, 0x89, 0x9d, 0xed, 0xa2, 0x86, 0x13, 0xa7, 0x64, 0x3c, 0xdf, 0x8c, 0xbf, 0xcf, 0xf3,
	0x03, 0xf3, 0x15, 0x65, 0x54, 0x30, 0x71, 0xb2, 0x2e, 0xb8, 0xe4, 0x68, 0xa4, 0x3e, 0xf8, 0x0c,
	0x66, 0xef, 0x78, 0x46, 0x59, 0x44, 0xbe, 0x96, 0x44, 0x48, 0x14, 0xc2, 0xa4, 0x14, 0xa4, 0x60,
	0xf1, 0x8a, 0x04, 0xde, 0x91, 0x77, 0x7c, 0x3d, 0x6a, 0xec, 0xca, 0xb7, 0x8e, 0x85, 0xd8, 0xf0,
	0x22, 0x0d, 0x06, 0xda, 0x57, 0xdb, 0xf8, 0x97, 0x07, 0x73, 0x93, 0x48, 0xac, 0x39, 0x13, 0x04,
	0x21, 0x18, 0x26, 0x3c, 0xd5, 0x59, 0xe6, 0x91, 0xfa, 0x47, 0xfb, 0xe0, 0xaf, 0x44, 0x66, 0x82,
	0xab, 0x5f, 0x74, 0x08, 0xe3, 0x2a, 0x3f, 0x4d, 0x03, 0x5f, 0xe1, 0x8c, 0xe5, 0xf0, 0x18, 0x5e,
	0xe6, 0xc1, 0x68, 0xf2, 0x45, 0xf9, 0x46, 0xda, 0x57, 0xdb, 0x68, 0x09, 0x23, 0xb2, 0x8a, 0x69,
	0x1e, 0x8c, 0x95, 0x43, 0x1b, 0x55, 0x04, 0x4d, 0x09, 0x93, 0x54, 0x7e, 0x0f, 0xae, 0xe9, 0x88,
	0xda, 0xc6, 0xf7, 0x15, 0x71, 0x5e, 0x4a, 0xeb, 0x09, 0x1a, 0xb0, 0xd7, 0x01, 0x3f, 0x81, 0x1b,
	0x35, 0xb8, 0x8f, 0x4c, 0xfc, 0xd3, 0x83, 0x9b, 0x11, 0xc9, 0xa8, 0x90, 0xa4, 0xa8, 0xef, 0x69,
	0xa5, 0x7b, 0x57, 0x4a, 0x1f, 0xfc, 0x45, 0xba, 0x7f, 0x95, 0xf4, 0xa1, 0x2d, 0x1d, 0xc1, 0x50,
	0xc4, 0xb9, 0x34, 0x0f, 0xa5, 0xfe, 0x9d, 0x42, 0x8e, 0x3b, 0x85, 0x7c, 0x06, 0xfb, 0x2d, 0xd1,
	0x5e, 0x1a, 0x37, 0x30, 0x7d, 0x93, 0xd2, 0x5d, 0x9e, 0xd1, 0x91, 0x31, 0xe8, 0xc8, 0xb0, 0xc9,
	0xf9, 0x2e, 0xb9, 0xed, 0x12, 0xf1, 0x0f, 0x0f, 0x66, 0xfa, 0xe6, 0xff, 0xaf, 0xf5, 0xf0, 0x5b,
	0x98, 0x9f, 0xf1, 0x3c, 0xe7, 0x9b, 0x1d, 0xdf, 0xe5, 0x93, 0x02, 0x13, 0xfd, 0x2e, 0xf3, 0xa8,
	0xb1, 0xab, 0xd6, 0xab, 0x13, 0xf5, 0x2a, 0xcb, 0x07, 0x38, 0xd0, 0x71, 0x39, 0x15, 0xd2, 0xea,
	0xbd, 0x75, 0x9c, 0x11, 0xc6, 0xeb, 0xde, 0xd3, 0x56, 0xa5, 0x21, 0xe1, 0x25, 0x93, 0xe6, 0x76,
	0x6d, 0x38, 0x94, 0xfd, 0xce, 0x44, 0xbc, 0x04, 0xb8, 0xa0, 0x2c, 0xcb, 0xc9, 0x7b, 0x41, 0x8a,
	0x7f, 0xe9, 0x69, 0x9c, 0x00, 0xb2, 0x09, 0xf6, 0xaa, 0xe1, 0x3d, 0x18, 0x55, 0x79, 0x44, 0xe0,
	0x1f, 0xf9, 0xc7, 0xd3, 0xd3, 0x03, 0xbd, 0xdc, 0x4e, 0x5a, 0x46, 0x91, 0xf6, 0xe3, 0x07, 0xb0,
	0x78, 0x55, 0xca, 0xcf, 0xe7, 0x86, 0xf6, 0x2e, 0xb3, 0xfe, 0x1c, 0x96, 0x6e, 0x48, 0x1f, 0x66,
	0xa7, 0xbf, 0x7d, 0x98, 0x56, 0x04, 0x2e, 0x48, 0xf1, 0x8d, 0x26, 0x04, 0x3d, 0x82, 0x91, 0xda,
	0x8f, 0x68, 0x61, 0x38, 0xda, 0x6b, 0x37, 0x5c, 0xba, 0x87, 0xfa, 0x26, 0xbc, 0x87, 0x9e, 0xc2,
	0x58, 0xef, 0x1b, 0x64, 0x21, 0xda, 0x5d, 0x15, 0xde, 0xea, 0x9c, 0x36, 0x81, 0x8f, 0x61, 0x52,
	0x8d, 0x84, 0x2a, 0x0a, 0x32, 0x20, 0x6b, 0x3a, 0xc3, 0x85, 0x73, 0xd6, 0x84, 0xbd, 0x80, 0x49,
	0x3d, 0xfd, 0xe8, 0xd0, 0x40, 0x3a, 0x7b, 0x2b, 0xbc, 0x7d, 0xe9, 0xdc, 0xa6, 0xab, 0x4b, 0xd9,
	0xd0, 0x75, 0x7a, 0xbf, 0xa1, 0xeb, 0x36, 0x32, 0xde, 0x43, 0xaf, 0x01, 0xda, 0x1e, 0x40, 0x81,
	0x03, 0xb3, 0xfa, 0x36, 0xbc, 0xb3, 0xc5, 0xd3, 0x24, 0x39, 0x87, 0x99, 0x5d, 0x30, 0x14, 0x1a,
	0xf0, 0x96, 0xc2, 0x87, 0x77, 0xb7, 0xfa, 0xea, 0x54, 0x1f, 0xc7, 0xca, 0xfb, 0xf0, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xf1, 0x90, 0xd6, 0xbf, 0x35, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	EditUser(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	Followlist(ctx context.Context, in *FollowlistRequest, opts ...grpc.CallOption) (*FollowlistResponse, error)
	AuthIdentity(ctx context.Context, in *AuthIdentityRequest, opts ...grpc.CallOption) (*AuthIdentityResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) EditUser(ctx context.Context, in *EditRequest, opts ...grpc.CallOption) (*EditResponse, error) {
	out := new(EditResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/EditUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Follow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Followlist(ctx context.Context, in *FollowlistRequest, opts ...grpc.CallOption) (*FollowlistResponse, error) {
	out := new(FollowlistResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Followlist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AuthIdentity(ctx context.Context, in *AuthIdentityRequest, opts ...grpc.CallOption) (*AuthIdentityResponse, error) {
	out := new(AuthIdentityResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/AuthIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	EditUser(context.Context, *EditRequest) (*EditResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Follow(context.Context, *FollowRequest) (*FollowResponse, error)
	Followlist(context.Context, *FollowlistRequest) (*FollowlistResponse, error)
	AuthIdentity(context.Context, *AuthIdentityRequest) (*AuthIdentityResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedUserServiceServer) EditUser(ctx context.Context, req *EditRequest) (*EditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUser not implemented")
}
func (*UnimplementedUserServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedUserServiceServer) Follow(ctx context.Context, req *FollowRequest) (*FollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (*UnimplementedUserServiceServer) Followlist(ctx context.Context, req *FollowlistRequest) (*FollowlistResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Followlist not implemented")
}
func (*UnimplementedUserServiceServer) AuthIdentity(ctx context.Context, req *AuthIdentityRequest) (*AuthIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthIdentity not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/EditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).EditUser(ctx, req.(*EditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Follow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Followlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Followlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Followlist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Followlist(ctx, req.(*FollowlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AuthIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AuthIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/AuthIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AuthIdentity(ctx, req.(*AuthIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _UserService_Logout_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _UserService_EditUser_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "Follow",
			Handler:    _UserService_Follow_Handler,
		},
		{
			MethodName: "Followlist",
			Handler:    _UserService_Followlist_Handler,
		},
		{
			MethodName: "AuthIdentity",
			Handler:    _UserService_AuthIdentity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "minisns.proto",
}
